server:
  port: 8080

# Actuator configuration
management:
  server:
    port: 9001
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: health
      base-path: /

# Dummy API URL as parameter
dummy-url: "https://dummyjson.com"